name: portfolio_website_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  url_launcher: ^6.1.14
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  font_awesome_flutter: ^10.5.0
  visibility_detector: ^0.4.0+2
  # google_fonts: ^6.2.0
  google_fonts: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
